--- #YAML:1.0
name:               Business-ISBN-Data
version:            20120719.001
abstract:           Data pack for Business::ISBN
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    File::Basename:       0
    File::Spec::Functions:  0
    Test::More:           0.95
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
